# Generated by Django 5.0.1 on 2024-02-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_petphoto_date_of_publication_alter_petphoto_pets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petphoto',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
