# Generated by Django 5.0.2 on 2024-02-24 11:49

import regular_exam.cars.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[regular_exam.cars.validators.validate_year]),
        ),
    ]
