# Generated by Django 5.0.1 on 2024-01-30 16:09

import petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_slug'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petphoto',
            name='date_of_publication',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='pets',
            field=models.ManyToManyField(blank=True, to='pets.pet'),
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='pet_photos/', validators=[petstagram.photos.validators.validate_file_size]),
        ),
    ]
