# Generated by Django 5.0.1 on 2024-02-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_person_age'),
        ('web', '0003_person_email'),
    ]

    operations = [
    ]
